services:
  redis:
    container_name: dev-redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - dev-redis-data:/data
    command: ["redis-server", "--save", "60", "1"]

volumes:
  dev-redis-data: